# Generated by Django 5.2.17 on 2026-08-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_content_type',
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
