# Generated by Django 5.2.17 on 2026-09-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(blank=True, choices=[('', 'Как в системе'), ('light', 'Светлая'), ('dark', 'Тёмная')], default='', max_length=10, verbose_name='Тема оформления'),
        ),
    ]
