# Generated by Django 5.2.17 on 2026-08-17 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True, verbose_name='Учётный период')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыт')),
            ],
            options={
                'ordering': ('-code',),
            },
        ),
        migrations.CreateModel(
            name='KpiTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=12, unique=True, verbose_name='План по прибыли от')),
            ],
            options={
                'ordering': ('threshold',),
            },
        ),
        migrations.CreateModel(
            name='ManagerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ставка смены')),
                ('leave_shift_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ставка отпускной смены')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerKpiRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='KPI, %')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.kpitier')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('manager', 'tier'), name='unique_manager_kpi_tier')],
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('manager', 'Менеджер'), ('printer', 'Печатник'), ('designer', 'Дизайнер')], max_length=16)),
                ('name', models.CharField(max_length=120, verbose_name='Сотрудник')),
                ('work_shifts', models.PositiveIntegerField(default=0, verbose_name='Рабочие смены')),
                ('leave_shifts', models.PositiveIntegerField(default=0, verbose_name='Отпускные/больничные смены')),
                ('shift_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leave_shift_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fixed_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Фиксированный оклад')),
                ('design_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость макетов')),
                ('design_percent', models.DecimalField(decimal_places=2, default=90, max_digits=5, verbose_name='Доля дизайнера, %')),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Аванс')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_lines', to='finance.financialperiod')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('period', 'manager'), name='unique_manager_period')],
            },
        ),
    ]
