# Generated by Django 5.2.17 on 2026-08-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollline',
            name='kpi_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Бонус KPI'),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='kpi_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='KPI, %'),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='order_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Прибыль по заказам'),
        ),
    ]
