# Generated by Django 5.2.17 on 2026-08-19 10:52

from django.db import migrations, models


def initialize_employee_settings(apps, schema_editor):
    ManagerSettings = apps.get_model("finance", "ManagerSettings")
    PayrollLine = apps.get_model("finance", "PayrollLine")
    for position, settings in enumerate(
        ManagerSettings.objects.order_by("user__first_name", "user__last_name", "user_id")
    ):
        settings.sort_order = position
        settings.save(update_fields=("sort_order",))
    PayrollLine.objects.filter(kind="designer").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_operatingexpense_periodexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='managersettings',
            name='design_percent',
            field=models.DecimalField(decimal_places=2, default=90, max_digits=5, verbose_name='Отчисление за макеты, %'),
        ),
        migrations.AddField(
            model_name='managersettings',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.RunPython(initialize_employee_settings, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='payrollline',
            name='kind',
            field=models.CharField(choices=[('manager', 'Сотрудник'), ('printer', 'Печатник')], max_length=16),
        ),
    ]
