# Generated by Django 5.2.17 on 2026-08-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderestimate',
            name='document_analysis',
            field=models.JSONField(blank=True, default=dict, verbose_name='Анализ документов'),
        ),
        migrations.AddField(
            model_name='tenderline',
            name='requirements',
            field=models.JSONField(blank=True, default=dict, verbose_name='Требования из ООЗ/ТЗ'),
        ),
    ]
