# Generated by Django 5.2.17 on 2026-08-24 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_process_routes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=500, verbose_name='Наименование позиции')),
                ('requirements', models.JSONField(blank=True, default=dict, verbose_name='Требования позиции')),
                ('current_hypothesis', models.JSONField(blank=True, default=dict, verbose_name='Текущая гипотеза')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_example', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='tenders.productiontrainingexample')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сессия обучения расчёту',
                'verbose_name_plural': 'Сессии обучения расчётам',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionTrainingTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('understood_changes', models.JSONField(blank=True, default=list, verbose_name='Понятые изменения')),
                ('hypothesis', models.JSONField(blank=True, default=dict, verbose_name='Версия расчёта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='tenders.productiontrainingsession')),
            ],
            options={
                'verbose_name': 'Версия обучающего диалога',
                'verbose_name_plural': 'Версии обучающих диалогов',
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
