# Generated by Django 5.2.17 on 2026-08-25 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_seed_confirmed_training_examples'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderKnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Источник')),
                ('supplier_name', models.CharField(blank=True, max_length=200, verbose_name='Поставщик')),
                ('source_type', models.CharField(choices=[('link', 'Ссылка'), ('document', 'Документ'), ('image', 'Изображение'), ('text', 'Текст'), ('catalog', 'Каталог / API')], max_length=20, verbose_name='Тип')),
                ('url', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка')),
                ('content_summary', models.TextField(blank=True, verbose_name='Извлечённые данные')),
                ('structured_data', models.JSONField(blank=True, default=dict, verbose_name='Структурированные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tender_knowledge_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Источник расчёта',
                'verbose_name_plural': 'Источники расчётов',
                'ordering': ['supplier_name', 'title', '-updated_at'],
            },
        ),
    ]
