# Generated by Django 5.2.17 on 2026-08-26 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0007_tenderknowledgesource'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=200, verbose_name='Поставщик')),
                ('base_url', models.URLField(max_length=500, verbose_name='Адрес API')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('sync_status', models.CharField(default='never', max_length=20, verbose_name='Состояние')),
                ('sync_message', models.CharField(blank=True, max_length=500, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Поставщик каталога',
                'verbose_name_plural': 'Поставщики каталогов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Готово'), ('failed', 'Ошибка')], default='running', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('received_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('deactivated_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='tenders.catalogsupplier')),
            ],
            options={
                'verbose_name': 'Синхронизация каталога',
                'verbose_name_plural': 'Синхронизации каталога',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, verbose_name='ID поставщика')),
                ('article', models.CharField(blank=True, max_length=120, verbose_name='Артикул')),
                ('article_base', models.CharField(blank=True, max_length=120, verbose_name='Базовый артикул')),
                ('group_id', models.CharField(blank=True, max_length=120, verbose_name='Группа товара')),
                ('color_group_id', models.CharField(blank=True, max_length=120, verbose_name='Группа цвета')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('full_name', models.CharField(blank=True, max_length=1000, verbose_name='Полное название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category_ids', models.JSONField(blank=True, default=list, verbose_name='Категории')),
                ('category_names', models.JSONField(blank=True, default=list, verbose_name='Названия категорий')),
                ('brand', models.CharField(blank=True, max_length=200, verbose_name='Бренд')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='Размер')),
                ('materials', models.JSONField(blank=True, default=list, verbose_name='Материалы')),
                ('colors', models.JSONField(blank=True, default=list, verbose_name='Цвета')),
                ('attributes', models.JSONField(blank=True, default=list, verbose_name='Характеристики')),
                ('branding', models.JSONField(blank=True, default=list, verbose_name='Виды нанесения')),
                ('package', models.JSONField(blank=True, default=list, verbose_name='Упаковка')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Цена')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Дилерская цена')),
                ('total_stock', models.IntegerField(default=0, verbose_name='Свободный остаток')),
                ('stock_moscow', models.IntegerField(default=0, verbose_name='Москва')),
                ('stock_remote', models.IntegerField(default=0, verbose_name='Удалённый склад')),
                ('stock_transit', models.IntegerField(default=0, verbose_name='В пути')),
                ('is_on_order', models.BooleanField(default=False, verbose_name='Под заказ')),
                ('delivery_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Дней до поставки')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='Изображение')),
                ('product_url', models.URLField(blank=True, max_length=1000, verbose_name='Карточка товара')),
                ('supply_terms', models.CharField(blank=True, max_length=1000, verbose_name='Условия поставки')),
                ('warning', models.CharField(blank=True, max_length=1000, verbose_name='Важное примечание')),
                ('defect', models.CharField(blank=True, max_length=1000, verbose_name='Дефекты')),
                ('search_text', models.TextField(blank=True, verbose_name='Поисковый индекс')),
                ('source_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Обновлено поставщиком')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Получено')),
                ('sync_marker', models.CharField(blank=True, db_index=True, editable=False, max_length=36)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Служебные данные')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenders.catalogsupplier')),
            ],
            options={
                'verbose_name': 'Товар каталога',
                'verbose_name_plural': 'Товары каталога',
                'ordering': ['supplier', 'name', 'article'],
                'indexes': [models.Index(fields=['supplier', 'is_active'], name='tenders_cat_supplie_d82b8b_idx'), models.Index(fields=['supplier', 'article'], name='tenders_cat_supplie_287fac_idx'), models.Index(fields=['supplier', 'group_id'], name='tenders_cat_supplie_27d40a_idx'), models.Index(fields=['supplier', 'total_stock'], name='tenders_cat_supplie_ef17ac_idx')],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'external_id'), name='unique_catalog_product_supplier_id')],
            },
        ),
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, verbose_name='ID поставщика')),
                ('parent_external_id', models.CharField(blank=True, max_length=100, verbose_name='Родительский ID')),
                ('name', models.CharField(max_length=300, verbose_name='Категория')),
                ('path', models.CharField(blank=True, max_length=1000, verbose_name='Полный путь')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tenders.catalogsupplier')),
            ],
            options={
                'verbose_name': 'Категория каталога',
                'verbose_name_plural': 'Категории каталога',
                'ordering': ['supplier', 'path', 'name'],
                'indexes': [models.Index(fields=['supplier', 'is_active'], name='tenders_cat_supplie_5ce75b_idx')],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'external_id'), name='unique_catalog_category_supplier_id')],
            },
        ),
    ]
