# Generated by Django 5.2.17 on 2026-08-26 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0008_catalogsupplier_catalogsyncrun_catalogproduct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogMatchDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('selected', 'Выбран'), ('rejected', 'Отклонён')], max_length=20, verbose_name='Решение')),
                ('reason_codes', models.JSONField(blank=True, default=list, verbose_name='Причины')),
                ('requirement_signature', models.JSONField(blank=True, default=dict, verbose_name='Требования на момент решения')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Учитывать в обучении')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_match_decisions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_decisions', to='tenders.catalogproduct')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_decisions', to='tenders.productiontrainingsession')),
            ],
            options={
                'verbose_name': 'Решение по товару каталога',
                'verbose_name_plural': 'Решения по товарам каталога',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['decision', 'is_confirmed'], name='tenders_cat_decisio_72e003_idx')],
            },
        ),
    ]
