# Generated by Django 5.2.17 on 2026-08-26 20:03

import django.db.models.deletion
from django.db import migrations, models


def preserve_product_identity(apps, schema_editor):
    Decision = apps.get_model('tenders', 'CatalogMatchDecision')
    for decision in Decision.objects.select_related('product__supplier').iterator():
        product = decision.product
        if not product:
            continue
        decision.supplier_code = product.supplier.code
        decision.product_external_id = product.external_id
        decision.product_article = product.article
        decision.product_snapshot = {
            'external_id': product.external_id,
            'article': product.article,
            'name': product.full_name or product.name,
            'url': product.product_url,
        }
        decision.save(update_fields=[
            'supplier_code', 'product_external_id', 'product_article', 'product_snapshot',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0009_catalogmatchdecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogmatchdecision',
            name='product_article',
            field=models.CharField(blank=True, max_length=120, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='catalogmatchdecision',
            name='product_external_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID товара поставщика'),
        ),
        migrations.AddField(
            model_name='catalogmatchdecision',
            name='product_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Карточка товара на момент решения'),
        ),
        migrations.AddField(
            model_name='catalogmatchdecision',
            name='supplier_code',
            field=models.CharField(default='oasis', max_length=50, verbose_name='Код поставщика'),
        ),
        migrations.RunPython(preserve_product_identity, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='catalogmatchdecision',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_decisions', to='tenders.catalogproduct'),
        ),
    ]
