# Generated by Django 5.2.17 on 2026-08-26 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0010_preserve_catalog_learning'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontrainingexample',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Используется в обучении'),
        ),
        migrations.AddField(
            model_name='productiontrainingexample',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_examples', to='tenders.productiontrainingexample'),
        ),
    ]
