# Generated by Django 5.2.17 on 2026-08-27 05:15

from django.db import migrations


def remove_legacy_oasis_cache(apps, schema_editor):
    """Switch Oasis to live API search without touching learned decisions."""
    CatalogProduct = apps.get_model('tenders', 'CatalogProduct')
    CatalogCategory = apps.get_model('tenders', 'CatalogCategory')
    CatalogSyncRun = apps.get_model('tenders', 'CatalogSyncRun')
    CatalogSupplier = apps.get_model('tenders', 'CatalogSupplier')

    # Migration 0010 copied every product referenced by a learning decision into
    # product_snapshot before making the foreign key optional, so these rows are
    # now only a disposable local search cache.
    CatalogProduct.objects.all().delete()
    CatalogCategory.objects.all().delete()
    CatalogSyncRun.objects.all().delete()
    CatalogSupplier.objects.filter(code='oasis').update(
        sync_status='live',
        sync_message='Живой поиск через API; локальная копия каталога отключена.',
        last_synced_at=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0011_version_training_examples'),
    ]

    operations = [
        migrations.RunPython(remove_legacy_oasis_cache, migrations.RunPython.noop),
    ]
