# Generated by Django 5.2.17 on 2026-08-27

import uuid

from django.db import migrations, models


def assign_knowledge_ids(apps, schema_editor):
    for model_name in ("ProductionTrainingExample", "TenderKnowledgeSource"):
        model = apps.get_model("tenders", model_name)
        for value in model.objects.filter(knowledge_id__isnull=True).iterator():
            value.knowledge_id = uuid.uuid4()
            value.save(update_fields=["knowledge_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0012_remove_legacy_oasis_cache"),
    ]

    operations = [
        migrations.AddField(
            model_name="productiontrainingexample",
            name="knowledge_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="productiontrainingexample",
            name="embedding",
            field=models.JSONField(blank=True, default=list, verbose_name="Смысловой индекс"),
        ),
        migrations.AddField(
            model_name="productiontrainingexample",
            name="embedding_model",
            field=models.CharField(blank=True, max_length=100, verbose_name="Модель смыслового индекса"),
        ),
        migrations.AddField(
            model_name="productiontrainingexample",
            name="embedding_updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Индекс обновлён"),
        ),
        migrations.AddField(
            model_name="tenderknowledgesource",
            name="knowledge_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(assign_knowledge_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="productiontrainingexample",
            name="knowledge_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="tenderknowledgesource",
            name="knowledge_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
