# Generated by Django 5.2.17 on 2026-08-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0014_catalogcategory_embeddings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderestimate',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'В ожидании'), ('lost', 'Проигран'), ('won', 'Выигран')], default='draft', max_length=16, verbose_name='Статус'),
        ),
    ]
