# Generated by Django 5.2.17 on 2026-09-04 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0016_tender_estimate_result_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSearchRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Правило')),
                ('source_phrase', models.CharField(blank=True, max_length=300, verbose_name='Из какой фразы обратной связи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_search_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Правило поиска по каталогу',
                'verbose_name_plural': 'Правила поиска по каталогу',
                'ordering': ['-created_at'],
            },
        ),
    ]
