# Generated by Django 5.2.17 on 2026-09-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0017_catalogsearchrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogsearchrule',
            name='action',
            field=models.CharField(choices=[('exclude', 'Минус-слово (исключить)'), ('include', 'Плюс-слово (обязательно искать)')], default='exclude', max_length=10, verbose_name='Действие'),
        ),
        migrations.AddField(
            model_name='catalogsearchrule',
            name='action_text',
            field=models.CharField(blank=True, max_length=120, verbose_name='Слово/корень для действия'),
        ),
        migrations.AddField(
            model_name='catalogsearchrule',
            name='label',
            field=models.CharField(blank=True, max_length=80, verbose_name='Короткая подпись для плашки'),
        ),
        migrations.AddField(
            model_name='catalogsearchrule',
            name='trigger_scope',
            field=models.CharField(choices=[('any', 'Название и ТЗ'), ('name', 'Только название'), ('requirements', 'Только ТЗ')], default='any', max_length=20, verbose_name='Где искать условие'),
        ),
        migrations.AddField(
            model_name='catalogsearchrule',
            name='trigger_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Условие (если пусто — всегда)'),
        ),
        migrations.AlterField(
            model_name='catalogsearchrule',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Правило целиком'),
        ),
    ]
