# Generated by Django 5.2.17 on 2026-09-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0018_catalogsearchrule_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogsearchrule',
            name='trigger_negate',
            field=models.BooleanField(default=False, verbose_name='Условие — это ОТСУТСТВИЕ слова'),
        ),
    ]
