# Generated by Django 5.2.17 on 2026-09-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0019_catalogsearchrule_trigger_negate'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogsearchrule',
            name='trigger_kind',
            field=models.CharField(choices=[('text', 'Слово/фраза (без ИИ)'), ('context', 'Числа/контекст (мини-ИИ на поиске)')], default='text', max_length=10, verbose_name='Тип условия'),
        ),
        migrations.AlterField(
            model_name='catalogsearchrule',
            name='trigger_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Условие (если пусто — всегда)'),
        ),
    ]
