# Generated by Django 5.2.17 on 2026-09-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0020_catalogsearchrule_trigger_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogsearchrule',
            name='action',
            field=models.CharField(choices=[('exclude', 'Минус-слово (исключить)'), ('include', 'Плюс-слово (обязательно искать)'), ('prefer', 'Мягкий приоритет (не исключает)')], default='exclude', max_length=10, verbose_name='Действие'),
        ),
    ]
