# Generated by Django 5.2.17 on 2026-09-05 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0021_alter_catalogsearchrule_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementSkipRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Название строки ТЗ')),
                ('label_normalized', models.CharField(max_length=200, unique=True, verbose_name='Название в нормальной форме')),
                ('example_value', models.CharField(blank=True, max_length=500, verbose_name='Пример значения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_skip_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Строка ТЗ вне подбора',
                'verbose_name_plural': 'Строки ТЗ вне подбора',
                'ordering': ['-created_at'],
            },
        ),
    ]
