# Generated by Django 5.2.17 on 2026-09-06 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0022_requirementskiprule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('catalog', 'Подбор товара'), ('requirements', 'Строки ТЗ'), ('route', 'Маршрут'), ('production_step', 'Этап производства'), ('cost', 'Себестоимость')], default='catalog', max_length=32, verbose_name='Область')),
                ('admin_text', models.TextField(verbose_name='Слова администратора')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='Чистая формулировка от ИИ')),
                ('item_word', models.CharField(blank=True, max_length=120, verbose_name='Слово-товар')),
                ('tz_labels', models.JSONField(blank=True, default=list, verbose_name='Метки полей ТЗ')),
                ('production_type', models.CharField(blank=True, max_length=120, verbose_name='Тип производства')),
                ('outcome', models.JSONField(blank=True, default=dict, verbose_name='Что вышло в прошлый раз')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_lessons', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='tenders.productiontrainingsession')),
            ],
            options={
                'verbose_name': 'Урок ассистента',
                'verbose_name_plural': 'Уроки ассистента',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scope', 'is_active'], name='tenders_les_scope_960e9f_idx')],
            },
        ),
    ]
