# Generated by Django 5.2.17 on 2026-09-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0023_lesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatalogSearchRule',
        ),
    ]
