# Generated by Django 5.2.17 on 2026-09-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0024_delete_catalogsearchrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CascadeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=16, verbose_name='Тип')),
                ('key', models.CharField(max_length=200, verbose_name='Ключ')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Содержимое')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Кэш каскада',
                'verbose_name_plural': 'Кэш каскада',
                'indexes': [models.Index(fields=['kind', 'key'], name='tenders_cas_kind_c4a702_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'key'), name='unique_cascade_cache_entry')],
            },
        ),
    ]
