# Generated by Django 5.2.17 on 2026-09-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenders", "0025_cascadecache"),
    ]

    operations = [
        migrations.CreateModel(
            name="CascadeLabCase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Название теста")),
                ("input_payload", models.JSONField(default=dict, verbose_name="Позиция и ТЗ")),
                ("custom_cards", models.JSONField(blank=True, default=list, verbose_name="Тестовые карточки")),
                ("expectations", models.JSONField(blank=True, default=dict, verbose_name="Ожидания")),
                ("settings", models.JSONField(blank=True, default=dict, verbose_name="Настройки шагов")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cascade_lab_cases", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "Тест лаборатории каскада", "verbose_name_plural": "Тесты лаборатории каскада", "ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="CascadeLabRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=500, verbose_name="Название")),
                ("input_payload", models.JSONField(default=dict, verbose_name="Исходный вход")),
                ("settings", models.JSONField(blank=True, default=dict, verbose_name="Настройки")),
                ("expectations", models.JSONField(blank=True, default=dict, verbose_name="Ожидания")),
                ("status", models.CharField(choices=[("draft", "Черновик"), ("running", "Выполняется"), ("paused", "Приостановлен"), ("completed", "Завершён"), ("error", "Ошибка")], default="draft", max_length=16, verbose_name="Статус")),
                ("current_step", models.PositiveSmallIntegerField(default=0, verbose_name="Последний шаг")),
                ("stop_after", models.PositiveSmallIntegerField(default=8, verbose_name="Остановиться после")),
                ("snapshots", models.JSONField(blank=True, default=list, verbose_name="Снимки шагов")),
                ("cascade_state", models.JSONField(blank=True, default=dict, verbose_name="Состояние каскада")),
                ("result", models.JSONField(blank=True, default=dict, verbose_name="Проверка ожиданий")),
                ("total_seconds", models.FloatField(default=0, verbose_name="Время, с")),
                ("total_cost_rub", models.FloatField(default=0, verbose_name="Стоимость, ₽")),
                ("error", models.TextField(blank=True, verbose_name="Ошибка")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cascade_lab_runs", to=settings.AUTH_USER_MODEL)),
                ("parent_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="forks", to="tenders.cascadelabrun")),
                ("source_line", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cascade_lab_runs", to="tenders.tenderline")),
                ("test_case", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="runs", to="tenders.cascadelabcase")),
            ],
            options={"verbose_name": "Прогон лаборатории каскада", "verbose_name_plural": "Прогоны лаборатории каскада", "ordering": ["-created_at"]},
        ),
    ]
