# Generated by Django 5.2.17 on 2026-09-11 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0026_cascadelabcase_cascadelabrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cascadelabrun',
            name='test_case',
        ),
        migrations.RemoveField(
            model_name='cascadelabrun',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cascadelabrun',
            name='parent_run',
        ),
        migrations.RemoveField(
            model_name='cascadelabrun',
            name='source_line',
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='family_key',
            field=models.CharField(blank=True, db_index=True, max_length=180, verbose_name='Нормализованное семейство'),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='variant_axes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Оси варианта'),
        ),
        migrations.AddField(
            model_name='tendersettings',
            name='auto_recalculate_requirements',
            field=models.BooleanField(default=False, verbose_name='Автопересчёт при изменении ТЗ'),
        ),
        migrations.AddField(
            model_name='tendersettings',
            name='auto_start_product_search',
            field=models.BooleanField(default=False, verbose_name='Автозапуск подбора при открытии'),
        ),
        migrations.CreateModel(
            name='CascadeConfigVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cascade_config_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Версия настроек каскада',
                'verbose_name_plural': 'Версии настроек каскада',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CascadeLabPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название набора')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки шагов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cascade_lab_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Набор настроек каскада',
                'verbose_name_plural': 'Наборы настроек каскада',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='CascadeLabCase',
        ),
        migrations.DeleteModel(
            name='CascadeLabRun',
        ),
        migrations.AddConstraint(
            model_name='cascadelabpreset',
            constraint=models.UniqueConstraint(fields=('created_by', 'name'), name='unique_cascade_lab_preset_name'),
        ),
    ]
