# Generated by Django 5.2.17 on 2026-09-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0027_final_cascade_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='embedding',
            field=models.JSONField(blank=True, default=list, verbose_name='Смысловой индекс'),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Модель смыслового индекса'),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='embedding_text_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='Хеш текста индекса'),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Индекс обновлён'),
        ),
    ]
