# Generated by Django 5.2.17 on 2026-09-16 08:41

from django.db import migrations, models

# Тот же сид, что и _UNIT_ALIAS_SEED в tenders/cascade.py — переносим в
# таблицу, чтобы он был виден и редактируем в админке с первого дня, а не
# спрятан только в коде (код на пустой таблице и так работает через
# fallback на сид, эта миграция — для видимости/редактируемости).
_SEED = {
    "г/м2": "г/м²", "г/м²": "г/м²", "гм2": "г/м²", "гм²": "г/м²", "г м2": "г/м²", "г м²": "г/м²",
    "g/m2": "г/м²", "g/m²": "г/м²", "gsm": "г/м²",
    "г/м3": "г/м³", "г/м³": "г/м³", "гм3": "г/м³", "гм³": "г/м³", "г м3": "г/м³", "г м³": "г/м³",
    "g/m3": "г/м³", "g/m³": "г/м³",
    "мм": "мм", "mm": "мм",
    "см": "см", "cm": "см",
    "мг": "мг", "mg": "мг",
    "кг": "кг", "kg": "кг",
    "мл": "мл", "ml": "мл",
    "лм": "лм", "lm": "лм",
    "кд": "кд", "cd": "кд",
}


def seed_unit_aliases(apps, schema_editor):
    UnitAlias = apps.get_model("tenders", "UnitAlias")
    UnitAlias.objects.bulk_create(
        [UnitAlias(spelling=spelling, canonical=canonical) for spelling, canonical in _SEED.items()],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0030_clean_active_catalog_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling', models.CharField(max_length=40, unique=True, verbose_name='Написание')),
                ('canonical', models.CharField(max_length=40, verbose_name='Каноническая единица')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Единица измерения — написание',
                'verbose_name_plural': 'Единицы измерения — написания',
                'ordering': ['canonical', 'spelling'],
            },
        ),
        migrations.RunPython(seed_unit_aliases, migrations.RunPython.noop),
    ]
