# Generated by Django 5.2.17 on 2026-09-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0031_unit_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderestimate',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Фактическая цена контракта'),
        ),
        migrations.AddField(
            model_name='tenderestimate',
            name='actual_reduction_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Фактическое снижение, %'),
        ),
        migrations.AddField(
            model_name='tenderestimate',
            name='outcome_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Итог внесён'),
        ),
        migrations.AddField(
            model_name='tenderestimate',
            name='outcome_source',
            field=models.CharField(blank=True, choices=[('auto', 'Автоматически'), ('manual', 'Вручную')], max_length=8, verbose_name='Источник итога'),
        ),
    ]
