# Generated by Django 5.2.17 on 2026-09-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0033_tenderestimate_tender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderestimate',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='В архиве с'),
        ),
    ]
