# Generated by Django 5.2.17 on 2026-09-23 06:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0034_tenderestimate_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendersettings',
            name='roi_good_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, verbose_name='ROI — зелёная зона, от %'),
        ),
        migrations.AddField(
            model_name='tendersettings',
            name='roi_thin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='ROI — жёлтая зона, от %'),
        ),
    ]
