# Generated by Django 5.2.17 on 2026-09-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0040_orderestimate_status_and_finalize_legacy_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderestimate',
            name='bid_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='Номер нашей заявки'),
        ),
        migrations.AddField(
            model_name='tenderestimate',
            name='bid_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Сумма нашей заявки'),
        ),
        migrations.AddField(
            model_name='tenderestimate',
            name='protocol',
            field=models.JSONField(blank=True, default=dict, verbose_name='Итоговый протокол (ЕИС)'),
        ),
        migrations.AddField(
            model_name='tenderestimate',
            name='protocol_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Протокол проверен'),
        ),
        migrations.AlterField(
            model_name='tenderestimate',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'В ожидании'), ('not_participated', 'Не участвовали'), ('lost', 'Проигран'), ('won', 'Выигран'), ('published', 'Итог опубликован')], default='draft', max_length=16, verbose_name='Статус'),
        ),
    ]
