# Generated by Django 5.2.17 on 2026-09-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0042_evaluation_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogproduct',
            name='variant_axes',
        ),
        migrations.CreateModel(
            name='AttributeConceptHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_key', models.CharField(db_index=True, max_length=200, verbose_name='Ключ понятия')),
                ('attribute_name', models.CharField(max_length=120, verbose_name='Название атрибута')),
                ('hits', models.PositiveIntegerField(default=1, verbose_name='Подтверждений')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Подсказка атрибута (словарь)',
                'verbose_name_plural': 'Подсказки атрибутов (словарь)',
                'ordering': ['-hits', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('concept_key', 'attribute_name'), name='unique_concept_attribute_hint')],
            },
        ),
    ]
