# Generated by Django 5.2.17 on 2026-09-27 16:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0044_seed_denier_unit_alias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='source',
            field=models.CharField(choices=[('manual', 'Вручную'), ('feedback', 'Из фидбэка'), ('proposal', 'Подтверждённое предложение'), ('import', 'Импорт'), ('preset', 'Стартовый набор')], default='feedback', max_length=16, verbose_name='Источник знания'),
        ),
        migrations.AddField(
            model_name='processdefinition',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, verbose_name='Параметры {required:[], optional:[]}'),
        ),
        migrations.AddField(
            model_name='processdefinition',
            name='performs_production',
            field=models.BooleanField(default=False, verbose_name='Выполняет производство'),
        ),
        migrations.AddField(
            model_name='processdefinition',
            name='scope_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Что производим'),
        ),
        migrations.AddField(
            model_name='processdefinition',
            name='supplies_input',
            field=models.BooleanField(default=False, verbose_name='Предоставляет изделие/материал'),
        ),
        migrations.AddField(
            model_name='processdefinition',
            name='terminal_mode',
            field=models.CharField(choices=[('always', 'Всегда'), ('never', 'Никогда'), ('sometimes', 'Иногда')], default='sometimes', max_length=10, verbose_name='Завершает маршрут'),
        ),
        migrations.AddField(
            model_name='processdefinition',
            name='when_not_to_use',
            field=models.TextField(blank=True, verbose_name='Когда не использовать'),
        ),
        migrations.AddField(
            model_name='processdefinition',
            name='when_to_use',
            field=models.TextField(blank=True, verbose_name='Когда использовать'),
        ),
        migrations.AddField(
            model_name='tenderknowledgesource',
            name='raw_file',
            field=models.BinaryField(blank=True, null=True, verbose_name='Файл источника'),
        ),
        migrations.AddField(
            model_name='tenderknowledgesource',
            name='raw_file_content_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='MIME-тип файла'),
        ),
        migrations.AddField(
            model_name='tenderknowledgesource',
            name='raw_file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя файла'),
        ),
        migrations.AddField(
            model_name='tenderknowledgesource',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_sources', to='tenders.tenderknowledgesource'),
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparties', to='tenders.catalogsupplier')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counterparties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tenderknowledgesource',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_sources', to='tenders.counterparty'),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, verbose_name='Группа предложений')),
                ('type', models.CharField(choices=[('create_stage', 'Новый этап'), ('update_stage', 'Изменить этап'), ('create_counterparty', 'Новый контрагент'), ('update_counterparty', 'Изменить контрагента'), ('link_stage_counterparty', 'Связать этап и контрагента'), ('create_lesson', 'Сохранить урок')], max_length=32, verbose_name='Тип')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Предлагаемая правка')),
                ('summary', models.CharField(max_length=300, verbose_name='Формулировка для карточки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус')),
                ('source_text', models.TextField(blank=True, verbose_name='Исходный фидбэк администратора')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда решили')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_proposals', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_proposals', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='tenders.productiontrainingsession')),
            ],
            options={
                'verbose_name': 'Предложение изменения базы производства',
                'verbose_name_plural': 'Предложения изменения базы производства',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'batch_id'], name='tenders_pro_status_a8d3ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='StageCounterpartyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Приоритет (меньше — важнее)')),
                ('price_source_type', models.CharField(choices=[('internal_calculator', 'Внутренний калькулятор'), ('catalog_api', 'Каталог / API'), ('price_list', 'Прайс-лист'), ('external_calculator', 'Внешний калькулятор'), ('external_api', 'Внешний API'), ('manual_quote', 'Ручной запрос цены'), ('historical', 'История цен')], default='manual_quote', max_length=24, verbose_name='Способ получения цены')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки (ограничения, параметры, сроки, минимальный заказ, ссылка на калькулятор…)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_links', to='tenders.counterparty')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparty_links', to='tenders.processdefinition')),
            ],
            options={
                'verbose_name': 'Связь этап ↔ контрагент',
                'verbose_name_plural': 'Связи этап ↔ контрагент',
                'ordering': ['priority', 'counterparty__name'],
                'constraints': [models.UniqueConstraint(fields=('stage', 'counterparty'), name='unique_stage_counterparty_link')],
            },
        ),
    ]
