# Generated by Django 5.2.17 on 2026-09-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0046_backfill_stage_flags_from_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderestimate',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На торгах'), ('not_participated', 'Не участвовали'), ('lost', 'Проигран'), ('won', 'Выигран')], default='draft', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tenderestimate',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На торгах'), ('not_participated', 'Не участвовали'), ('lost', 'Проигран'), ('won', 'Выигран'), ('published', 'Итог опубликован')], default='draft', max_length=16, verbose_name='Статус'),
        ),
    ]
