# Generated by Django 5.2.17 on 2026-10-06 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_selection', '0036_tender_notification_error'),
        ('tenders', '0052_step4_decision_cache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerFeedbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('scope', models.CharField(default='current_tender', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(max_length=64)),
                ('scope_context', models.JSONField(blank=True, default=dict)),
                ('applicability', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('status', models.CharField(default='draft', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenders.knowledgerecord')),
                ('feedback_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenders.ownerfeedbackevent')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='open', max_length=24)),
                ('engine_key', models.CharField(blank=True, max_length=100)),
                ('question', models.TextField()),
                ('reason', models.TextField(blank=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('possible_answers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tender_selection.tender')),
            ],
        ),
        migrations.AddField(
            model_name='ownerfeedbackevent',
            name='interaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_events', to='tenders.ownerinteraction'),
        ),
        migrations.CreateModel(
            name='TenderComputeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('preparing_input', 'Preparing Input'), ('routing', 'Routing'), ('preparing', 'Preparing'), ('partial', 'Partial'), ('ready', 'Ready'), ('needs_review', 'Needs Review'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('running', 'Running')], default='queued', max_length=24)),
                ('version', models.CharField(default='v2', max_length=64)),
                ('trigger', models.CharField(default='manual', max_length=64)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('error', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v2_compute_jobs', to='tender_selection.tender')),
            ],
        ),
        migrations.CreateModel(
            name='TenderComputeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('route_key', models.CharField(blank=True, max_length=100)),
                ('engine_key', models.CharField(blank=True, max_length=100)),
                ('route_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('route_metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenders.tendercomputejob')),
            ],
        ),
        migrations.AddField(
            model_name='ownerinteraction',
            name='compute_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenders.tendercomputeline'),
        ),
        migrations.CreateModel(
            name='TenderComputeWorkUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_key', models.CharField(max_length=100)),
                ('dedupe_key', models.CharField(max_length=128)),
                ('input_fingerprint', models.CharField(max_length=128)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_units', to='tenders.tendercomputejob')),
                ('lines', models.ManyToManyField(related_name='work_units', to='tenders.tendercomputeline')),
            ],
        ),
        migrations.CreateModel(
            name='TenderComputePreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_key', models.CharField(max_length=100)),
                ('preparation_key', models.CharField(max_length=100)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('freshness', models.CharField(blank=True, max_length=64)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.JSONField(blank=True, default=dict)),
                ('work_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparations', to='tenders.tendercomputeworkunit')),
            ],
        ),
        migrations.AddField(
            model_name='ownerinteraction',
            name='work_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenders.tendercomputeworkunit'),
        ),
        migrations.CreateModel(
            name='TenderSourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=160)),
                ('source_type', models.CharField(default='notification', max_length=32)),
                ('original_text', models.TextField()),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('requirements', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_items', to='tenders.tendersourceitem')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_items', to='tenders.tendersourceitem')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v2_source_items', to='tender_selection.tender')),
            ],
        ),
        migrations.AddField(
            model_name='tendercomputeline',
            name='source_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compute_lines', to='tenders.tendersourceitem'),
        ),
        migrations.AddField(
            model_name='ownerinteraction',
            name='source_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenders.tendersourceitem'),
        ),
        migrations.AddConstraint(
            model_name='tendercomputeworkunit',
            constraint=models.UniqueConstraint(fields=('job', 'engine_key', 'dedupe_key'), name='unique_v2_work_unit'),
        ),
        migrations.AddConstraint(
            model_name='tendercomputepreparation',
            constraint=models.UniqueConstraint(fields=('work_unit', 'engine_key', 'preparation_key'), name='unique_v2_preparation'),
        ),
        migrations.AddConstraint(
            model_name='tendersourceitem',
            constraint=models.UniqueConstraint(fields=('tender', 'source_key'), name='unique_v2_source_item'),
        ),
        migrations.AddConstraint(
            model_name='tendercomputeline',
            constraint=models.UniqueConstraint(fields=('job', 'source_item'), name='unique_v2_compute_line'),
        ),
    ]
