# Generated by Django 5.2.17 on 2026-08-17 14:13

import django.core.validators
import django.db.models.deletion
from datetime import date
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def create_initial_reconciliation(apps, schema_editor):
    CashReconciliation = apps.get_model('cash', 'CashReconciliation')
    CashReconciliation.objects.get_or_create(
        effective_date=date(2026, 8, 17),
        defaults={
            'cash_balance': Decimal('403.00'),
            'card_balance': Decimal('84993.00'),
            'note': 'Стартовый остаток',
        },
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(unique=True, verbose_name='Дата сверки')),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Наличные на утро')),
                ('card_balance', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Карта на утро')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сверка остатков',
                'verbose_name_plural': 'Сверки остатков',
                'ordering': ('-effective_date',),
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField(db_index=True, verbose_name='Дата операции')),
                ('account', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта')], max_length=10, verbose_name='Счёт')),
                ('direction', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма')),
                ('reason', models.CharField(max_length=255, verbose_name='Основание / № заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Операция кассы',
                'verbose_name_plural': 'Операции кассы',
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='CashAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создано'), ('updated', 'Изменено'), ('deleted', 'Удалено'), ('reconciled', 'Сверка')], max_length=16)),
                ('message', models.TextField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_audit_events', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='cash.cashtransaction')),
            ],
            options={
                'verbose_name': 'История кассы',
                'verbose_name_plural': 'История кассы',
                'ordering': ('-occurred_at', '-pk'),
            },
        ),
        migrations.RunPython(create_initial_reconciliation, migrations.RunPython.noop),
    ]
