# Generated by Django 5.2.17 on 2026-09-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True, verbose_name='ID операции в банке')),
                ('status', models.CharField(blank=True, max_length=32, verbose_name='Статус в банке')),
                ('direction', models.CharField(blank=True, max_length=16, verbose_name='Направление')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('currency', models.CharField(default='RUR', max_length=3, verbose_name='Валюта')),
                ('counterparty_name', models.CharField(blank=True, max_length=255, verbose_name='Плательщик')),
                ('counterparty_inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН плательщика')),
                ('counterparty_account', models.CharField(blank=True, max_length=34, verbose_name='Счёт плательщика')),
                ('counterparty_bank', models.CharField(blank=True, max_length=255, verbose_name='Банк плательщика')),
                ('payment_purpose', models.TextField(blank=True, verbose_name='Назначение платежа')),
                ('doc_number', models.CharField(blank=True, max_length=32, verbose_name='№ документа')),
                ('account_number', models.CharField(blank=True, max_length=34, verbose_name='Счёт зачисления')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения')),
                ('operation_date', models.DateField(db_index=True, verbose_name='Дата операции')),
                ('hidden_from_managers', models.BooleanField(default=False, verbose_name='Скрыт от менеджеров')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Ответ банка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Платёж из банка',
                'verbose_name_plural': 'Платежи из банка',
                'ordering': ('-operation_date', '-executed_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='BankSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('last_status', models.CharField(blank=True, max_length=255, verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Состояние синхронизации с банком',
                'verbose_name_plural': 'Состояние синхронизации с банком',
            },
        ),
    ]
