# Generated by Django 5.2.17 on 2026-09-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_bankpayment_banksyncstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpayment',
            name='is_internal',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Перевод между своими счетами'),
        ),
        migrations.AddField(
            model_name='banksyncstate',
            name='own_identifiers',
            field=models.JSONField(blank=True, default=list, verbose_name='Свои реквизиты'),
        ),
    ]
