from django.urls import path

from . import assistant_ui, views

urlpatterns = [
    path("assistant/", assistant_ui.console, name="assistant_console"),
    path("", views.home, name="tender_home"),
    path("cascade-lab/", views.cascade_lab, name="cascade_lab"),
    path("cascade-lab/execute/", views.cascade_lab_execute, name="cascade_lab_execute"),
    path("cascade-lab/presets/save/", views.cascade_lab_preset_save, name="cascade_lab_preset_save"),
    path("cascade-lab/settings/activate/", views.cascade_lab_activate, name="cascade_lab_activate"),
    path("knowledge/sync/", views.knowledge_sync, name="tender_knowledge_sync"),
    path("catalog/sync/", views.catalog_sync, name="tender_catalog_sync"),
    path("catalog/gifts/import-test/", views.gifts_import_test, name="gifts_import_test"),
    path("catalog/gifts/raw-sample/", views.gifts_raw_sample, name="gifts_raw_sample"),
    path("catalog/oasis/import-test/", views.oasis_import_test, name="oasis_import_test"),
    path("import/preview/", views.import_preview, name="tender_import_preview"),
    path("import/ai/", views.ai_import_preview, name="tender_ai_import_preview"),
    path("documents/inspect/", views.document_inspect, name="tender_document_inspect"),
    path("documents/analyze/", views.document_preview, name="tender_document_preview"),
    path("import/requirements/", views.technical_requirements_preview, name="tender_requirements_preview"),
    path("production/route/", views.production_route_preview, name="tender_production_route_preview"),
    path("production/route/<int:session_id>/", views.production_route_status, name="tender_production_route_status"),
    path("production/reopen/", views.reopen_production_hypothesis, name="tender_reopen_production_hypothesis"),
    path("production/revise/", views.revise_production_hypothesis, name="tender_revise_production_hypothesis"),
    path("production/confirm-stage/", views.confirm_proposed_stage, name="tender_confirm_proposed_stage"),
    path("production/catalog/select/", views.select_catalog_product, name="tender_select_catalog_product"),
    path("production/source/", views.add_calculation_source, name="tender_add_calculation_source"),
    path("production/confirm/", views.confirm_production_type, name="tender_confirm_production_type"),
    path("production/requirement-skip/drop/", views.drop_requirement_skip_rule, name="tender_drop_requirement_skip_rule"),
    path("production/base/", views.production_base_data, name="tender_production_base"),
    path("production/base/providers/", views.provider_list, name="provider_list"),
    path("production/base/providers/add/", views.provider_create, name="provider_create"),
    path("production/base/providers/<int:provider_id>/", views.provider_detail, name="provider_detail"),
    path("production/base/providers/knowledge/<int:version_id>/", views.provider_knowledge_review, name="provider_knowledge_review"),
    path("production/base/providers/calculator/<int:binding_id>/", views.provider_calculator, name="provider_calculator"),
    path("production/base/counterparty/draft/", views.production_counterparty_draft, name="tender_production_counterparty_draft"),
    path("production/base/counterparty/confirm/", views.production_counterparty_confirm, name="tender_production_counterparty_confirm"),
    path("production/base/feedback/draft/", views.production_feedback_draft, name="tender_production_feedback_draft"),
    path("production/base/feedback/confirm/", views.production_feedback_confirm, name="tender_production_feedback_confirm"),
    path("production/lesson/drop/", views.drop_lesson, name="tender_drop_lesson"),
    path("production/route-knowledge/drop/", views.drop_route_knowledge, name="tender_drop_route_knowledge"),
    path("production/knowledge/", views.calculator_knowledge_proposal, name="tender_calculator_knowledge_proposal"),
    path("save/", views.save_estimate, name="tender_estimate_create"),
    path("order/<int:pk>/", views.home, name="tender_estimate"),
    path("order/<int:pk>/save/", views.save_estimate, name="tender_estimate_save"),
    path("order/<int:pk>/duplicate/", views.duplicate_estimate, name="tender_estimate_duplicate"),
    path("order/<int:pk>/delete/", views.delete_estimate, name="tender_estimate_delete"),
    path("order/<int:pk>/status/", views.update_order_status, name="order_estimate_status"),
    path("<int:pk>/", views.legacy_estimate_redirect, name="tender_estimate_legacy"),
    path("pipeline/", views.home, {"pipeline": True, "minimal": True}, name="tender_pipeline_home"),
    path("pipeline/save/", views.save_estimate, {"pipeline": True}, name="tender_pipeline_estimate_create"),
    path("pipeline/<int:pk>/", views.home, {"pipeline": True, "minimal": True}, name="tender_pipeline_estimate"),
    path("pipeline/<int:pk>/save/", views.save_estimate, {"pipeline": True}, name="tender_pipeline_estimate_save"),
    path("pipeline/<int:pk>/duplicate/", views.duplicate_estimate, {"pipeline": True}, name="tender_pipeline_estimate_duplicate"),
    path("pipeline/<int:pk>/delete/", views.delete_estimate, {"pipeline": True}, name="tender_pipeline_estimate_delete"),
    path("pipeline/<int:pk>/status/", views.update_estimate_status, name="tender_pipeline_estimate_status"),
    # Тот же TenderEstimate, но открытый из «Расчётов» (не из карточки тендера) —
    # менеджеру без доступа к «Тендерам» здесь показывается блок рисков вместо
    # ссылки на карточку.
    path("tender/<int:pk>/", views.home, {"pipeline": True}, name="tender_worklist_estimate"),
    path("tender/<int:pk>/save/", views.save_estimate, {"pipeline": True}, name="tender_worklist_estimate_save"),
]
