# Generated by Django 5.2.17 on 2026-09-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Номер закупки')),
                ('object_info', models.TextField(verbose_name='Наименование объекта закупки (как в ЕИС)')),
                ('title', models.TextField(blank=True, verbose_name='Название')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='НМЦК')),
                ('currency_code', models.CharField(blank=True, max_length=8, verbose_name='Валюта')),
                ('customer_inn', models.CharField(blank=True, max_length=32, verbose_name='ИНН заказчика')),
                ('region', models.PositiveIntegerField(blank=True, null=True, verbose_name='Код региона')),
                ('stage', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этап')),
                ('purchase_type', models.CharField(blank=True, max_length=64, verbose_name='Тип закупки')),
                ('okpd2', models.JSONField(blank=True, default=list, verbose_name='ОКПД2')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано')),
                ('collecting_finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание подачи заявок')),
                ('eis_url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка на ЕИС')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Ответ API')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('dismissed', 'Скрыт'), ('pushed', 'Передан в расчёт')], default='new', max_length=16, verbose_name='Статус')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='Впервые найден')),
                ('last_pulled_at', models.DateTimeField(verbose_name='Последняя выгрузка')),
            ],
            options={
                'verbose_name': 'Найденный тендер',
                'verbose_name_plural': 'Найденные тендеры',
                'ordering': ['-published_at', '-first_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='PullRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='Параметры запроса')),
                ('requests_made', models.PositiveIntegerField(default=0, verbose_name='Запросов к API')),
                ('records_received', models.PositiveIntegerField(default=0, verbose_name='Получено записей')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='Новых')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='Обновлено')),
                ('duration_seconds', models.FloatField(default=0.0, verbose_name='Длительность, сек')),
                ('ok', models.BooleanField(default=False, verbose_name='Успех')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Выгрузка',
                'verbose_name_plural': 'Выгрузки',
                'ordering': ['-started_at'],
            },
        ),
    ]
