# Generated by Django 5.2.17 on 2026-09-07 18:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_selection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_words', models.TextField(blank=True, help_text='Через запятую или с новой строки. Тендер проходит, если в названии есть хотя бы одно. Знак + внутри — «все части сразу»: живых+цветов = оба слова. Пусто — берём все.', verbose_name='Плюс-слова')),
                ('exclude_words', models.TextField(blank=True, help_text='Через запятую или с новой строки. Если в названии есть хотя бы одно — тендер скрывается.', verbose_name='Минус-слова')),
                ('min_price', models.DecimalField(decimal_places=2, default=Decimal('300000'), max_digits=16, verbose_name='Минимальная НМЦК, ₽')),
                ('window_days', models.PositiveSmallIntegerField(default=7, verbose_name='Окно по дате публикации, дней')),
            ],
            options={
                'verbose_name': 'Настройки подбора',
                'verbose_name_plural': 'Настройки подбора',
            },
        ),
    ]
