# Generated by Django 5.2.17 on 2026-09-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_selection', '0002_filtersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='ИНН')),
                ('name', models.CharField(blank=True, max_length=400, verbose_name='Название')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='Город')),
                ('region_name', models.CharField(blank=True, max_length=200, verbose_name='Регион')),
                ('checked_at', models.DateTimeField(auto_now=True, verbose_name='Проверено')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
    ]
