# Generated by Django 5.2.17 on 2026-09-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_selection', '0003_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundtender',
            name='notification_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Извещение загружено'),
        ),
        migrations.AddField(
            model_name='foundtender',
            name='notification_raw',
            field=models.JSONField(blank=True, default=dict, verbose_name='Извещение (сырое)'),
        ),
    ]
