# Generated by Django 5.2.17 on 2026-09-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_selection', '0004_foundtender_notification_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundtender',
            name='review',
            field=models.CharField(choices=[('unreviewed', 'Не проверен'), ('interesting', 'Интересно'), ('not_interesting', 'Не интересно')], default='unreviewed', max_length=16, verbose_name='Проверка'),
        ),
    ]
