# Generated by Django 5.2.17 on 2026-09-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_selection', '0005_foundtender_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtersettings',
            name='laws',
            field=models.JSONField(blank=True, default=list, verbose_name='Источники'),
        ),
        migrations.AddField(
            model_name='filtersettings',
            name='okpd2_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='Категории ОКПД2'),
        ),
        migrations.AddField(
            model_name='filtersettings',
            name='regions',
            field=models.JSONField(blank=True, default=list, verbose_name='Регионы (коды)'),
        ),
        migrations.AddField(
            model_name='foundtender',
            name='law',
            field=models.CharField(choices=[('fz44', '44-ФЗ'), ('fz223', '223-ФЗ')], db_index=True, default='fz44', max_length=8, verbose_name='Закон'),
        ),
        migrations.AddField(
            model_name='foundtender',
            name='pushed_estimate_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID просчёта'),
        ),
        migrations.AlterField(
            model_name='foundtender',
            name='purchase_number',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Номер закупки'),
        ),
        migrations.AddConstraint(
            model_name='foundtender',
            constraint=models.UniqueConstraint(fields=('law', 'purchase_number'), name='uniq_law_purchase_number'),
        ),
    ]
