# Generated by Django 5.2.17 on 2026-09-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_selection', '0006_filtersettings_laws_filtersettings_okpd2_codes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundtender',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('dismissed', 'Скрыт'), ('pushed', 'На расчёте')], default='new', max_length=16, verbose_name='Статус'),
        ),
    ]
