# Generated by Django 5.2.17 on 2026-09-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_selection', '0007_alter_foundtender_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=600, unique=True, verbose_name='Ссылка')),
                ('filename', models.CharField(blank=True, max_length=400, verbose_name='Имя файла')),
                ('kind', models.CharField(blank=True, max_length=16, verbose_name='Тип')),
                ('html', models.TextField(blank=True, verbose_name='Содержимое (HTML)')),
                ('error', models.CharField(blank=True, max_length=400, verbose_name='Ошибка')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='Загружено')),
            ],
            options={
                'verbose_name': 'Предпросмотр документа',
                'verbose_name_plural': 'Предпросмотры документов',
            },
        ),
    ]
