# Generated by Django 5.2.17 on 2026-09-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_selection', '0008_documentpreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=400, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='organization',
            name='short_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Короткое название'),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, max_length=200, verbose_name='Сайт'),
        ),
    ]
