# Generated by Django 5.2.17 on 2026-09-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_selection', '0009_organization_address_organization_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundtender',
            name='clarifications_raw',
            field=models.JSONField(blank=True, default=list, verbose_name='Разъяснения (сырое)'),
        ),
        migrations.AddField(
            model_name='foundtender',
            name='complaints_raw',
            field=models.JSONField(blank=True, default=list, verbose_name='Жалобы (сырое)'),
        ),
        migrations.AddField(
            model_name='foundtender',
            name='extras_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Разъяснения/жалобы загружены'),
        ),
    ]
