# Generated by Django 5.2.17 on 2026-09-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_selection', '0010_foundtender_clarifications_raw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('requests_made', models.PositiveIntegerField(default=0, verbose_name='Запросов к API')),
                ('contracts_seen', models.PositiveIntegerField(default=0, verbose_name='Контрактов просмотрено')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='Новых строк')),
                ('filled_count', models.PositiveIntegerField(default=0, verbose_name='Добрано начальных цен')),
                ('duration_seconds', models.FloatField(default=0.0, verbose_name='Длительность, сек')),
                ('ok', models.BooleanField(default=False, verbose_name='Успех')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Сбор статистики',
                'verbose_name_plural': 'Сборы статистики',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law', models.CharField(db_index=True, default='fz44', max_length=8, verbose_name='Закон')),
                ('purchase_number', models.CharField(db_index=True, max_length=40, verbose_name='Номер закупки')),
                ('contract_reg_num', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Номер контракта')),
                ('shared_purchase', models.BooleanField(db_index=True, default=False, verbose_name='Совместная / многолотовая закупка')),
                ('category', models.CharField(blank=True, db_index=True, max_length=12, verbose_name='Категория (группа ОКПД2)')),
                ('okpd2', models.JSONField(blank=True, default=list, verbose_name='Коды ОКПД2')),
                ('ktru', models.JSONField(blank=True, default=list, verbose_name='Коды КТРУ')),
                ('region', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Код региона')),
                ('subject', models.TextField(blank=True, verbose_name='Предмет контракта')),
                ('nmck', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Начальная цена (НМЦК)')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Итоговая цена контракта')),
                ('discount_pct', models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=5, null=True, verbose_name='Снижение, %')),
                ('participants_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Участников')),
                ('winner_inn', models.CharField(blank=True, max_length=32, verbose_name='ИНН победителя')),
                ('is_ours', models.BooleanField(default=False, verbose_name='Наш тендер')),
                ('contract_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата контракта')),
                ('nmck_checked', models.BooleanField(db_index=True, default=False, verbose_name='Начальная цена добрана')),
                ('collected_at', models.DateTimeField(auto_now=True, verbose_name='Собрано')),
            ],
            options={
                'verbose_name': 'Статистика по контракту',
                'verbose_name_plural': 'Статистика по контрактам',
                'ordering': ['-contract_date', '-collected_at'],
                'constraints': [models.UniqueConstraint(fields=('law', 'contract_reg_num'), name='uniq_stat_law_reg')],
            },
        ),
    ]
