# Generated by Django 5.2.17 on 2026-09-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_selection', '0011_statsrun_contractstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractstat',
            name='customer_inn',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='ИНН заказчика'),
        ),
    ]
