# Generated by Django 5.2.17 on 2026-09-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_selection', '0014_plus_words_pechati'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundtender',
            name='risk_assessment',
            field=models.JSONField(blank=True, default=dict, verbose_name='Оценка рисков'),
        ),
        migrations.AddField(
            model_name='foundtender',
            name='risk_assessment_docs',
            field=models.JSONField(blank=True, default=list, verbose_name='Документы, использованные при оценке'),
        ),
        migrations.AddField(
            model_name='foundtender',
            name='risk_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Риски оценены'),
        ),
        migrations.AddField(
            model_name='foundtender',
            name='risk_error',
            field=models.CharField(blank=True, max_length=400, verbose_name='Ошибка оценки рисков'),
        ),
    ]
