# Generated by Django 5.2.17 on 2026-09-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_selection', '0015_foundtender_risk_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundtender',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Открыт пользователем (впервые)'),
        ),
    ]
