# Generated by Django 5.2.17 on 2026-09-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_selection', '0020_remove_legacy_pushed_estimate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundtender',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='В архиве с'),
        ),
        migrations.AlterField(
            model_name='foundtender',
            name='review',
            field=models.CharField(choices=[('unreviewed', 'Не проверен'), ('interesting', 'В работе')], default='unreviewed', max_length=16, verbose_name='Проверка'),
        ),
    ]
