# Generated by Django 5.2.17 on 2026-09-27 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_selection', '0028_evaluation_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law', models.CharField(default='fz44', max_length=8, verbose_name='Закон')),
                ('purchase_number', models.CharField(max_length=40, verbose_name='Номер закупки')),
                ('title', models.TextField(blank=True, verbose_name='Название')),
                ('okpd2', models.JSONField(blank=True, default=list, verbose_name='ОКПД2')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='НМЦК')),
                ('plus_hits', models.JSONField(blank=True, default=list, verbose_name='Сработавшие плюс-слова')),
                ('filtered_out', models.BooleanField(default=False, verbose_name='Скрыт словами')),
                ('was_opened', models.BooleanField(default=False, verbose_name='Открывали')),
                ('purged_at', models.DateTimeField(auto_now_add=True, verbose_name='Удалён')),
            ],
            options={
                'verbose_name': 'След удалённого тендера',
                'verbose_name_plural': 'Следы удалённых тендеров',
            },
        ),
        migrations.CreateModel(
            name='WordAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Запущен')),
                ('model', models.CharField(blank=True, max_length=80, verbose_name='Модель')),
                ('input_counts', models.JSONField(blank=True, default=dict, verbose_name='Сколько примеров отправлено')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Предложения')),
                ('spend_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Стоимость, ₽')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI-аудит слов',
                'verbose_name_plural': 'AI-аудиты слов',
                'ordering': ['-created_at'],
            },
        ),
    ]
