# Generated by Django 5.2.17 on 2026-09-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_selection', '0029_incoming_trace_and_word_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtersettings',
            name='keyword_pull_cursor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
