# Generated by Django 5.2.17 on 2026-09-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_selection', '0030_filtersettings_keyword_pull_cursor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='bid_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='Номер нашей заявки'),
        ),
        migrations.AddField(
            model_name='tender',
            name='bid_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Сумма нашей заявки'),
        ),
        migrations.AddField(
            model_name='tender',
            name='contract_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Контракт проверен'),
        ),
        migrations.AddField(
            model_name='tender',
            name='contract_exe_end',
            field=models.DateField(blank=True, null=True, verbose_name='Исполнение контракта по'),
        ),
        migrations.AddField(
            model_name='tender',
            name='contract_exe_start',
            field=models.DateField(blank=True, null=True, verbose_name='Исполнение контракта с'),
        ),
        migrations.AddField(
            model_name='tender',
            name='contract_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Фактическая цена контракта'),
        ),
        migrations.AddField(
            model_name='tender',
            name='contract_reduction_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Фактическое снижение, %'),
        ),
        migrations.AddField(
            model_name='tender',
            name='contract_reg_num',
            field=models.CharField(blank=True, max_length=40, verbose_name='Номер контракта'),
        ),
        migrations.AddField(
            model_name='tender',
            name='outcome_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Итог внесён'),
        ),
        migrations.AddField(
            model_name='tender',
            name='outcome_source',
            field=models.CharField(blank=True, choices=[('auto', 'Автоматически'), ('manual', 'Вручную')], max_length=8, verbose_name='Источник итога'),
        ),
        migrations.AddField(
            model_name='tender',
            name='outcome_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На торгах'), ('not_participated', 'Не участвовали'), ('lost', 'Проигран'), ('won', 'Выигран'), ('published', 'Итог опубликован')], default='draft', max_length=16, verbose_name='Стадия сделки'),
        ),
        migrations.AddField(
            model_name='tender',
            name='protocol',
            field=models.JSONField(blank=True, default=dict, verbose_name='Итоговый протокол (ЕИС)'),
        ),
        migrations.AddField(
            model_name='tender',
            name='protocol_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Протокол проверен'),
        ),
    ]
