# Generated by Django 5.2.17 on 2026-09-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_selection', '0031_tender_bid_number_tender_bid_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractstat',
            name='own_funnel',
            field=models.BooleanField(db_index=True, default=False, help_text='Пришло из наших Входящих/Архива, а не из общего скана рынка по категориям.', verbose_name='Из своей воронки'),
        ),
    ]
