# Generated by Django 5.2.17 on 2026-10-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tender_selection", "0037_tender_market_forecast")]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="profile_model",
            field=models.CharField(blank=True, max_length=100, verbose_name="Модель проверки профиля"),
        ),
        migrations.AddField(
            model_name="tender",
            name="profile_reason",
            field=models.CharField(blank=True, max_length=500, verbose_name="Причина рекомендации ИИ"),
        ),
    ]
