# Generated by Django 5.2.17 on 2026-10-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tender_selection", "0038_tender_profile_agent_reason")]

    operations = [
        migrations.AlterField(
            model_name="filtersettings",
            name="profile_triage_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Gemini ставит объяснимую рекомендацию после плюс/минус-слов, но ничего не скрывает автоматически.",
                verbose_name="ИИ: проверять новые входящие по профилю",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="profile_checked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="ИИ проверил профиль"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="profile_confidence",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name="Уверенность ИИ по профилю"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="profile_signal",
            field=models.CharField(
                blank=True,
                choices=[("", "Не проверен"), ("clear", "Похоже, по профилю"), ("doubt", "Нужно проверить"), ("not_profile", "Возможно, не по профилю")],
                max_length=16,
                verbose_name="Сигнал ИИ по профилю",
            ),
        ),
    ]
