# Generated by Django 4.2.27 on 2026-04-10 15:30

from django.db import migrations, models
import payroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrecord',
            name='accounting_period',
            field=models.CharField(db_index=True, default=payroll.models.current_accounting_period, max_length=7),
        ),
    ]
