# Generated by Django 5.2.17 on 2026-08-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_orderrecord_accounting_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrecord',
            name='record_type',
            field=models.CharField(choices=[('order', 'Заказ'), ('design', 'Макет')], db_index=True, default='order', max_length=10, verbose_name='Тип записи'),
        ),
    ]
