# Generated by Django 5.2.17 on 2026-08-17 18:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('550.00'), max_digits=12, verbose_name='Цена часа')),
                ('material_coefficient', models.DecimalField(decimal_places=3, default=Decimal('2.000'), max_digits=7, verbose_name='Коэффициент материала')),
                ('time_coefficient', models.DecimalField(decimal_places=3, default=Decimal('1.500'), max_digits=7, verbose_name='Коэффициент времени')),
                ('regular_discount', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Скидка постоянника, %')),
                ('partner_discount', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='Скидка контрагента, %')),
                ('urgency_multiplier', models.DecimalField(decimal_places=3, default=Decimal('1.500'), max_digits=7, verbose_name='Коэффициент без очереди')),
            ],
            options={
                'verbose_name': 'Настройки листового калькулятора',
                'verbose_name_plural': 'Настройки листового калькулятора',
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новый расчёт', max_length=200)),
                ('product_quantity', models.PositiveIntegerField(default=1, verbose_name='Тираж конечного изделия')),
                ('work_hours', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8, verbose_name='Рабочие часы')),
                ('settings_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculator_estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Расчёт',
                'verbose_name_plural': 'Сохранённые расчёты',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('paper', 'Бумага'), ('konica', 'Печать · Konica'), ('xerox', 'Печать · Xerox'), ('postpress', 'Постпечатная обработка'), ('embossing', 'Тиснение')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('unit_name', models.CharField(default='ед.', max_length=40)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('price_multiplier', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('base_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_items', to='calculator.priceitem')),
            ],
            options={
                'verbose_name': 'Позиция калькулятора',
                'verbose_name_plural': 'Справочник калькулятора',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EstimateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('paper', 'Бумага'), ('konica', 'Печать · Konica'), ('xerox', 'Печать · Xerox'), ('postpress', 'Постпечатная обработка'), ('embossing', 'Тиснение')], max_length=20)),
                ('name_snapshot', models.CharField(max_length=200)),
                ('unit_name', models.CharField(default='ед.', max_length=40)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_custom', models.BooleanField(default=False)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='calculator.estimate')),
                ('price_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculator.priceitem')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
