# Generated by Django 5.2.17 on 2026-08-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_seed_sheet_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='summary_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
