# Generated by Django 5.2.17 on 2026-08-24 08:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def seed_known_aliases(apps, schema_editor):
    PriceItem = apps.get_model('calculator', 'PriceItem')
    PriceItem.objects.filter(category='embossing').update(aliases='тиснение, горячее тиснение, тиснение фольгой, фольгирование, тиснение серебром')
    PriceItem.objects.filter(name__icontains='Пружина').update(aliases='пружина, металлическая пружина, брошюровка на пружину, переплёт на пружину')


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_estimate_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceitem',
            name='aliases',
            field=models.TextField(blank=True, help_text='Через запятую: горячее тиснение, тиснение фольгой', verbose_name='Синонимы для ИИ'),
        ),
        migrations.CreateModel(
            name='ProductionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_kind', models.CharField(choices=[('direct', 'Обычная единица каталога'), ('linear', 'Расход по длине из упаковки / бобины')], default='direct', max_length=20, verbose_name='Способ расчёта')),
                ('package_quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Например, длина намотки в метрах', max_digits=12, verbose_name='Количество в упаковке')),
                ('waste_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Технологический отход, %')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Технологическое примечание')),
                ('price_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_rule', to='calculator.priceitem', verbose_name='Позиция калькулятора')),
            ],
            options={
                'verbose_name': 'Правило производственного расчёта',
                'verbose_name_plural': 'Правила производственного расчёта',
            },
        ),
        migrations.RunPython(seed_known_aliases, migrations.RunPython.noop),
    ]
