# Generated by Django 5.2.17 on 2026-09-14 10:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_priceitem_aliases_productionrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatorsettings',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='НДС, %'),
        ),
    ]
